-- Reimbursements app - upgrade to v2
-- Run this ONCE in your EXISTING Supabase project's SQL Editor
-- (Dashboard -> SQL Editor -> New query -> paste this whole file -> Run).
--
-- What this changes:
--   1. Adds a `settlements` table - payments you record toward the total you
--      owe. You can pay it off fully or partially in one go, instead of
--      settling each bill one at a time.
--   2. Lets both you and your brother edit your own bills/pocket-money
--      entries (not just delete them), and lets the payer edit or delete
--      anything.
--   3. Carries forward any bills you already marked "settled" under the old
--      system into the new `settlements` ledger, so your running total
--      stays accurate.
--   4. Removes the old per-bill status/settled_at/settled_by columns, since
--      "settled" is now tracked as a running total rather than per bill.
--
-- Safe to run more than once - every step below is written to skip work
-- that's already done.

-- ---------------------------------------------------------------------------
-- 1. New settlements table
-- ---------------------------------------------------------------------------
create table if not exists settlements (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  date date not null,
  note text,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now()
);

alter table settlements enable row level security;

drop policy if exists "settlements are readable by any logged-in user" on settlements;
create policy "settlements are readable by any logged-in user"
  on settlements for select
  using (auth.uid() is not null);

drop policy if exists "only payer can record a settlement" on settlements;
create policy "only payer can record a settlement"
  on settlements for insert
  with check (
    created_by = auth.uid()
    and exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "only payer can edit a settlement" on settlements;
create policy "only payer can edit a settlement"
  on settlements for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

drop policy if exists "only payer can delete a settlement" on settlements;
create policy "only payer can delete a settlement"
  on settlements for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

create index if not exists idx_settlements_date on settlements(date);

-- ---------------------------------------------------------------------------
-- 2. Drop the old policies that reference the status column FIRST - Postgres
--    won't let you drop a column that a policy still depends on.
-- ---------------------------------------------------------------------------
drop policy if exists "only payer can settle or unsettle" on reimbursements;
drop policy if exists "delete own pending bill, or payer deletes any pending bill" on reimbursements;

-- ---------------------------------------------------------------------------
-- 3. Carry forward any already-settled bills into the new ledger, THEN drop
--    the old status columns. The "if column exists" guard means this block
--    only does anything the first time you run it - safe to re-run.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'reimbursements' and column_name = 'status'
  ) then
    insert into settlements (amount, date, note, created_by)
    select amount,
           coalesce(settled_at::date, date),
           'Carried forward from an earlier per-bill settlement',
           coalesce(settled_by, uploaded_by)
    from reimbursements
    where status = 'settled';
  end if;
end $$;

alter table reimbursements drop column if exists status;
alter table reimbursements drop column if exists settled_at;
alter table reimbursements drop column if exists settled_by;

drop index if exists idx_reimb_status;

-- ---------------------------------------------------------------------------
-- 4. New reimbursements edit/delete policies (no longer status-dependent).
-- ---------------------------------------------------------------------------
drop policy if exists "edit own bill, or payer edits any bill" on reimbursements;
create policy "edit own bill, or payer edits any bill"
  on reimbursements for update
  using (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  )
  with check (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "delete own bill, or payer deletes any bill" on reimbursements;
create policy "delete own bill, or payer deletes any bill"
  on reimbursements for delete
  using (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

-- ---------------------------------------------------------------------------
-- 5. Let the payer edit pocket money entries too (delete already existed).
-- ---------------------------------------------------------------------------
drop policy if exists "only payer can edit pocket money" on pocket_money;
create policy "only payer can edit pocket money"
  on pocket_money for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

-- ---------------------------------------------------------------------------
-- 6. Replace get_summary(): now based on the settlements ledger instead of
--    per-bill status. Note the return columns changed - the app's
--    JavaScript has been updated to match (pull the latest js/app.js).
-- ---------------------------------------------------------------------------
drop function if exists get_summary(date);

create function get_summary(as_of date default current_date)
returns table (
  as_of_out date,
  pocket_money_total numeric,
  reimbursement_total numeric,
  settlement_total numeric,
  amount_owed numeric
)
language sql
security invoker
stable
as $$
  select
    as_of,
    coalesce((select sum(amount) from pocket_money where date <= as_of), 0),
    coalesce((select sum(amount) from reimbursements where date <= as_of), 0),
    coalesce((select sum(amount) from settlements where date <= as_of), 0),
    coalesce((select sum(amount) from reimbursements where date <= as_of), 0)
      - coalesce((select sum(amount) from settlements where date <= as_of), 0)
$$;

grant execute on function get_summary(date) to authenticated;

-- Done. You can now deploy the updated js/app.js (and the rest of this
-- folder) - see README.md for the "Updating the app later" steps.
