-- Reimbursements app - upgrade to v3
-- Run this ONCE in your EXISTING Supabase project's SQL Editor
-- (Dashboard -> SQL Editor -> New query -> paste this whole file -> Run).
--
-- What this changes:
--   1. Adds an `audit_log` table that automatically records every insert,
--      edit, and delete on bills, pocket money, and payments - who did it,
--      when, and the full before/after values. This is driven by database
--      triggers, not app code, so it can't be missed even if the app gains
--      new ways to change data later.
--   2. Only the payer role can read the audit log (RLS-enforced) - your
--      brother won't see this tab.
--
-- This does NOT touch or rewrite any existing data - it only starts
-- recording changes from the moment you run this. Past history (before
-- today) isn't reconstructed, since there was nothing capturing it yet.
--
-- Safe to run more than once - every step below is written to skip work
-- that's already done.

-- ---------------------------------------------------------------------------
-- 1. The audit_log table itself.
-- ---------------------------------------------------------------------------
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_id bigint not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_data jsonb,
  new_data jsonb,
  changed_by uuid references profiles(id),
  changed_at timestamptz not null default now()
);

alter table audit_log enable row level security;

drop policy if exists "only payer can view audit log" on audit_log;
create policy "only payer can view audit log"
  on audit_log for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

-- No insert/update/delete policies on purpose - rows are only ever written
-- by the trigger function below (which runs with elevated privileges), never
-- directly by the app or a user.

create index if not exists idx_audit_log_changed_at on audit_log(changed_at desc);
create index if not exists idx_audit_log_table_row on audit_log(table_name, row_id);

-- ---------------------------------------------------------------------------
-- 2. The trigger function. security definer means it runs with the
--    privileges of whoever owns it (you, running this in the SQL Editor -
--    an elevated role), so it can write to audit_log even though ordinary
--    users have no insert policy on that table. It captures whichever role
--    was actually logged in via auth.uid() at the time of the change.
-- ---------------------------------------------------------------------------
create or replace function log_audit_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'DELETE') then
    insert into audit_log (table_name, row_id, action, old_data, new_data, changed_by)
    values (tg_table_name, old.id, 'delete', to_jsonb(old), null, auth.uid());
    return old;
  elsif (tg_op = 'UPDATE') then
    insert into audit_log (table_name, row_id, action, old_data, new_data, changed_by)
    values (tg_table_name, new.id, 'update', to_jsonb(old), to_jsonb(new), auth.uid());
    return new;
  elsif (tg_op = 'INSERT') then
    insert into audit_log (table_name, row_id, action, old_data, new_data, changed_by)
    values (tg_table_name, new.id, 'insert', null, to_jsonb(new), auth.uid());
    return new;
  end if;
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- 3. Attach the trigger to each table we want tracked.
-- ---------------------------------------------------------------------------
drop trigger if exists trg_audit_reimbursements on reimbursements;
create trigger trg_audit_reimbursements
  after insert or update or delete on reimbursements
  for each row execute function log_audit_change();

drop trigger if exists trg_audit_pocket_money on pocket_money;
create trigger trg_audit_pocket_money
  after insert or update or delete on pocket_money
  for each row execute function log_audit_change();

drop trigger if exists trg_audit_settlements on settlements;
create trigger trg_audit_settlements
  after insert or update or delete on settlements
  for each row execute function log_audit_change();

-- Done. You can now deploy the updated js/app.js and index.html (and the
-- rest of this folder) - see README.md for the "Updating the app later"
-- steps. The Activity tab will start filling in the moment someone adds,
-- edits, or deletes a bill, pocket money entry, or payment.
