-- Reimbursements app - Supabase schema (v2)
-- Run this once in your Supabase project's SQL Editor (Dashboard -> SQL Editor -> New query),
-- for a BRAND NEW project only.
--
-- Already have a project running the earlier version of this app? Do NOT run
-- this file - run supabase/migration_v2.sql instead, which upgrades your
-- existing tables in place without losing data.
--
-- Safe to re-run: uses "if not exists" / "or replace" where possible.

-- ---------------------------------------------------------------------------
-- Profiles: maps each Supabase Auth user to a role + display name.
-- You create the two Auth users by hand in the dashboard (see README), then
-- insert their rows here.
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('payer', 'brother')),
  display_name text not null
);

alter table profiles enable row level security;

drop policy if exists "profiles are readable by any logged-in user" on profiles;
create policy "profiles are readable by any logged-in user"
  on profiles for select
  using (auth.uid() is not null);

-- No insert/update/delete policies on purpose: with only two fixed accounts,
-- you manage this table yourself from the SQL Editor (which uses an
-- elevated role that bypasses RLS), not from the app.

-- ---------------------------------------------------------------------------
-- Pocket money: a running log the payer adds to. Both roles can view it;
-- only the payer can add, edit, or remove entries.
-- ---------------------------------------------------------------------------
create table if not exists pocket_money (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  date date not null,
  note text,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now()
);

alter table pocket_money enable row level security;

drop policy if exists "pocket money is readable by any logged-in user" on pocket_money;
create policy "pocket money is readable by any logged-in user"
  on pocket_money for select
  using (auth.uid() is not null);

drop policy if exists "only payer can add pocket money" on pocket_money;
create policy "only payer can add pocket money"
  on pocket_money for insert
  with check (
    created_by = auth.uid()
    and exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "only payer can edit pocket money" on pocket_money;
create policy "only payer can edit pocket money"
  on pocket_money for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

drop policy if exists "only payer can delete pocket money" on pocket_money;
create policy "only payer can delete pocket money"
  on pocket_money for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

-- ---------------------------------------------------------------------------
-- Reimbursements: bills/receipts submitted for reimbursement.
-- Brother sees only his own; payer sees everything. There's no per-bill
-- "settled" status any more - what's owed is simply the running total of
-- all bills minus all payments recorded in `settlements` below, so you can
-- pay it off in full or in part without matching payments to specific bills.
-- ---------------------------------------------------------------------------
create table if not exists reimbursements (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  description text not null,
  image_path text,
  date date not null,
  uploaded_by uuid not null references profiles(id),
  created_at timestamptz not null default now()
);

alter table reimbursements enable row level security;

drop policy if exists "payer sees all, brother sees own" on reimbursements;
create policy "payer sees all, brother sees own"
  on reimbursements for select
  using (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "either role can submit their own bill" on reimbursements;
create policy "either role can submit their own bill"
  on reimbursements for insert
  with check (uploaded_by = auth.uid());

drop policy if exists "edit own bill, or payer edits any bill" on reimbursements;
create policy "edit own bill, or payer edits any bill"
  on reimbursements for update
  using (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  )
  with check (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "delete own bill, or payer deletes any bill" on reimbursements;
create policy "delete own bill, or payer deletes any bill"
  on reimbursements for delete
  using (
    uploaded_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

create index if not exists idx_reimb_date on reimbursements(date);
create index if not exists idx_pocket_date on pocket_money(date);

-- ---------------------------------------------------------------------------
-- Settlements: payments the payer makes toward the total outstanding balance.
-- Each one can be a full or partial payment - it's just an amount taken off
-- the running total, not tied to any specific bill. Both roles can view the
-- history; only the payer can record, edit, or remove one.
-- ---------------------------------------------------------------------------
create table if not exists settlements (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  date date not null,
  note text,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now()
);

alter table settlements enable row level security;

drop policy if exists "settlements are readable by any logged-in user" on settlements;
create policy "settlements are readable by any logged-in user"
  on settlements for select
  using (auth.uid() is not null);

drop policy if exists "only payer can record a settlement" on settlements;
create policy "only payer can record a settlement"
  on settlements for insert
  with check (
    created_by = auth.uid()
    and exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer')
  );

drop policy if exists "only payer can edit a settlement" on settlements;
create policy "only payer can edit a settlement"
  on settlements for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

drop policy if exists "only payer can delete a settlement" on settlements;
create policy "only payer can delete a settlement"
  on settlements for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'payer'));

create index if not exists idx_settlements_date on settlements(date);

-- ---------------------------------------------------------------------------
-- Dashboard summary, computed "as of" a given day (defaults to today).
-- Runs with the caller's own permissions, so it naturally respects the
-- select policies above (only meaningful when called by the payer).
-- ---------------------------------------------------------------------------
create or replace function get_summary(as_of date default current_date)
returns table (
  as_of_out date,
  pocket_money_total numeric,
  reimbursement_total numeric,
  settlement_total numeric,
  amount_owed numeric
)
language sql
security invoker
stable
as $$
  select
    as_of,
    coalesce((select sum(amount) from pocket_money where date <= as_of), 0),
    coalesce((select sum(amount) from reimbursements where date <= as_of), 0),
    coalesce((select sum(amount) from settlements where date <= as_of), 0),
    coalesce((select sum(amount) from reimbursements where date <= as_of), 0)
      - coalesce((select sum(amount) from settlements where date <= as_of), 0)
$$;

grant execute on function get_summary(date) to authenticated;

-- ---------------------------------------------------------------------------
-- Storage bucket for receipt photos. Private (not public) - files are only
-- reachable via short-lived signed URLs generated by the app for logged-in
-- users.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false)
on conflict (id) do nothing;

drop policy if exists "logged-in users can read receipts" on storage.objects;
create policy "logged-in users can read receipts"
  on storage.objects for select
  using (bucket_id = 'receipts' and auth.uid() is not null);

drop policy if exists "logged-in users can upload receipts" on storage.objects;
create policy "logged-in users can upload receipts"
  on storage.objects for insert
  with check (bucket_id = 'receipts' and auth.uid() is not null);
